/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.Player;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import view.util.ComboBoxRenderer;

/**
 *
 * @author david
 */
@Deprecated
public class Launcher extends JFrame {

    /**
     * Creates new form Launcher
     */
    private ComboBoxRenderer renderer;
    private Integer array[];
    
    private Player player1;
    private Player player2;
    
    public Launcher() {
        renderer = new ComboBoxRenderer();
        array = new Integer[8];
        for(int i = 0; i < 8; i++) {
            array[i] = i;
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player2TextField = new javax.swing.JTextField();
        player2Label = new javax.swing.JLabel();
        player2ComboBox = new javax.swing.JComboBox(array);
        btReady2 = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        playerOptionPanel = new javax.swing.JPanel();
        player1Label = new javax.swing.JLabel();
        player1TextField = new javax.swing.JTextField();
        player1ComboBox = new javax.swing.JComboBox(array);
        btReady1 = new javax.swing.JButton();

        player2TextField.setColumns(16);
        player2TextField.setText("Player 2");

        player2Label.setBackground(new java.awt.Color(255, 255, 255));
        player2Label.setText("Player 2");
        player2Label.setOpaque(true);

        player2ComboBox.setSelectedIndex(1);
        player2ComboBox.setRenderer(renderer);

        btReady2.setBackground(new java.awt.Color(255, 255, 255));
        btReady2.setText("Ready");
        btReady2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReady2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Launcher");
        setResizable(false);

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        titleLabel.setText("OmokAI");

        playerOptionPanel.setLayout(new java.awt.GridLayout(4, 2, 5, 0));

        player1Label.setBackground(new java.awt.Color(0, 0, 0));
        player1Label.setForeground(new java.awt.Color(255, 255, 255));
        player1Label.setText("Player");
        player1Label.setOpaque(true);
        playerOptionPanel.add(player1Label);
        player1Label.setHorizontalAlignment(SwingConstants.CENTER);

        player1TextField.setBackground(new java.awt.Color(0, 0, 0));
        player1TextField.setColumns(16);
        player1TextField.setForeground(new java.awt.Color(255, 255, 255));
        player1TextField.setText("Human");
        playerOptionPanel.add(player1TextField);

        player1ComboBox.setBackground(new java.awt.Color(0, 0, 0));
        player1ComboBox.setForeground(new java.awt.Color(255, 255, 255));
        player1ComboBox.setSelectedIndex(0);
        player1ComboBox.setRenderer(renderer);
        playerOptionPanel.add(player1ComboBox);

        btReady1.setBackground(new java.awt.Color(0, 0, 0));
        btReady1.setForeground(new java.awt.Color(255, 255, 255));
        btReady1.setText("Ready");
        btReady1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReady1ActionPerformed(evt);
            }
        });
        playerOptionPanel.add(btReady1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerOptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerOptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        titleLabel.setHorizontalAlignment(SwingConstants.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btReady1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReady1ActionPerformed
        if(player2ComboBox.getSelectedItem() != player1ComboBox.getSelectedItem()) {
            btReady1.setEnabled(false);
            player1ComboBox.setEnabled(false);
            player1TextField.setEnabled(false);
            player1 = new Player(player1TextField.getText(), (Integer) player1ComboBox.getSelectedItem());      
            //new Game(player1).setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "You can't pick this piece!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btReady1ActionPerformed

    private void btReady2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReady2ActionPerformed
        if(player2ComboBox.getSelectedItem() != player1ComboBox.getSelectedItem()) {
            btReady2.setEnabled(false);
            player2ComboBox.setEnabled(false);
            player2TextField.setEnabled(false);
            player2 = new Player(player2TextField.getText(), (Integer) player2ComboBox.getSelectedItem());            
            if(!btReady1.isEnabled()) {
                //new Game(player1).setVisible(true);
                dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "The pieces must be different!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btReady2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btReady1;
    private javax.swing.JButton btReady2;
    private javax.swing.JComboBox<String> player1ComboBox;
    private javax.swing.JLabel player1Label;
    private javax.swing.JTextField player1TextField;
    private javax.swing.JComboBox<String> player2ComboBox;
    private javax.swing.JLabel player2Label;
    private javax.swing.JTextField player2TextField;
    private javax.swing.JPanel playerOptionPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
